<?php

namespace Database\Seeders;

use App\Models\Master\Bidang;
use App\Models\Master\Perusahaan;
use App\Models\Master\StatusPekerjaan;
use App\Models\Master\TenagaAhli;
use App\Models\Pekerjaan;
use App\Models\PekerjaanPersonil;
use Illuminate\Database\Seeder;

/**
 * RealPekerjaan2026Seeder — import 72 proyek nyata DPUTR Kab. Bandung TA 2026
 * Source: D:/Downloads/coding project/project_management/1_PEKERJAAN 2026.xlsx
 * Generated otomatis dari xlsx -> JSON -> seeder.
 *
 * Run: php artisan db:seed --class=RealPekerjaan2026Seeder
 */
class RealPekerjaan2026Seeder extends Seeder
{
    public function run(): void
    {
        // Cache lookups
        $bidangIds = Bidang::pluck('id', 'kode')->toArray();
        $statusIds = StatusPekerjaan::pluck('id', 'kode')->toArray();

        // Ensure vendors exist (firstOrCreate per nama)
        $vendorMap = [];
        $vendors = ["CV. IMAYA CONSULTING ENGINEERS", "CV. TACIBA SHIGOTO NUSANTARA", "KONSULTAN PERORANGAN", "PT. ADHI CITRABHUMI UTAMA", "PT. BINARTHAMA KHARISMA", "PT. DWINA KARYA UTAMA", "PT. GANESA INOVASI", "PT. GANESA PRATAMA CONSULTAN", "PT. HERANDAS ENGINEER SYSTEM", "PT. ITERGO BUANA UTAMA", "PT. JASAPLAN REKANAN UTAMA", "PT. MARTHA TRIA SELARAS", "PT. MULTI PRANATA MANDIRI NUSANTARA", "PT. PRIMAREKA CIPTA MANDIRI", "PT. PURNA WAHANA LESTARI", "PT. PURNA WAHANA LESTARI KONSULTAN"];
        foreach ($vendors as $name) {
            $jenis = str_starts_with($name, 'CV') ? 'CV' : 'PT';
            $perusahaan = Perusahaan::firstOrCreate(
                ['nama' => $name],
                ['jenis' => $jenis, 'is_blacklisted' => false],
            );
            $vendorMap[$name] = $perusahaan->id;
        }

        // Seed pekerjaan rows
        $rows = [
            [
                'bidang_kode' => 'BG',
                'nama' => 'Kajian Geoteknik Stabilitas Tanah',
                'vendor' => 'PT. ITERGO BUANA UTAMA',
                'pagu' => 99594750.0,
                'no_spk' => '602.1/10/SPK/Kajian.Geoteknik.Tanah/BG-DPUTR/2026',
                'tgl_spk' => '2026-01-05',
                'no_spmk' => '602.1/10/SPMK/Kajian.Geoteknik.Tanah/BG-DPUTR/2026',
                'tgl_mulai' => '2026-01-05',
                'tgl_akhir' => '2026-02-03',
                'hari' => 30,
                'status_kode' => 'selesai',
                'personil' => [
                    [
                        'nama' => 'Rian Hendiawan, S.T.',
                        'jabatan' => 'Team Leader/Tenaga Ahli Geoteknik',
                        'nilai' => 17000000,
                    ],
                    [
                        'nama' => 'Nurbania, S.T',
                        'jabatan' => 'Teknisi Lapangan',
                        'nilai' => 9350000,
                    ],
                    [
                        'nama' => 'Agus Hermawan',
                        'jabatan' => 'Drafter',
                        'nilai' => 6500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Kajian Pemetaan Topografi',
                'vendor' => 'PT. PURNA WAHANA LESTARI KONSULTAN',
                'pagu' => 99511500.0,
                'no_spk' => '602.1/09/SPK/Kajian.Topografi/BG-DPUTR/2026',
                'tgl_spk' => '2026-01-05',
                'no_spmk' => '602.1/09/SPMK/Kajian.Topografi/BG-DPUTR/2026',
                'tgl_mulai' => '2026-01-05',
                'tgl_akhir' => '2026-02-03',
                'hari' => 30,
                'status_kode' => 'selesai',
                'personil' => [
                    [
                        'nama' => 'Aditya Garisya Bagaskara, ST',
                        'jabatan' => 'Team Leader/Tenaga Ahli Sipil',
                        'nilai' => 19000000,
                    ],
                    [
                        'nama' => 'Anton Yanto Rusli, ST',
                        'jabatan' => 'Surveyor',
                        'nilai' => 4400000,
                    ],
                    [
                        'nama' => 'Tri Agus Widodo, ST',
                        'jabatan' => 'Surveyor',
                        'nilai' => 4400000,
                    ],
                    [
                        'nama' => 'Agus Supriatna',
                        'jabatan' => 'Asisten Surveyor',
                        'nilai' => 3250000,
                    ],
                    [
                        'nama' => 'Siti Zahra Fauziah',
                        'jabatan' => 'Asisten Surveyor',
                        'nilai' => 3250000,
                    ],
                    [
                        'nama' => 'Ridwan Jujun Saparudin',
                        'jabatan' => 'Drafter',
                        'nilai' => 6500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Pengawasan Rehab Berat Kantor DALDUKPPA',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [
                    [
                        'nama' => 'Aditya Garisya Bagaskara, ST',
                        'jabatan' => 'Team Leader',
                        'nilai' => null,
                    ],
                    [
                        'nama' => 'Nadya Eiranti',
                        'jabatan' => 'Pengawas Gedung',
                        'nilai' => null,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Renovasi Gedung SAT Intelkam dan Lanjutan Pembangunan Lantai 2 Gedung Sembilan Enam Polresta Bandung',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'proses_desain',
                'personil' => [
                    [
                        'nama' => 'SURYADI',
                        'jabatan' => 'Ahli Arsitek – TM',
                        'nilai' => null,
                    ],
                    [
                        'nama' => 'IRVAN KEMAL BANUYA',
                        'jabatan' => 'Tenaga Ahli Sipil',
                        'nilai' => null,
                    ],
                    [
                        'nama' => 'Supriadi Agustian, ST',
                        'jabatan' => 'ELK 7 (Ahli Elektrikal)',
                        'nilai' => null,
                    ],
                    [
                        'nama' => 'AHMAD IHZA FARESI, ST',
                        'jabatan' => 'Quantity',
                        'nilai' => null,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Pembangunan Pagar RSUD Arjasari',
                'vendor' => 'PT. MARTHA TRIA SELARAS',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [
                    [
                        'nama' => 'Ir. Joko Budiono',
                        'jabatan' => 'TM',
                        'nilai' => null,
                    ],
                    [
                        'nama' => 'Danang Mahendra, SST',
                        'jabatan' => 'Tenaga Ahli Sipil',
                        'nilai' => null,
                    ],
                    [
                        'nama' => 'Muh Mustakim',
                        'jabatan' => 'Juru Gambar',
                        'nilai' => null,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Pembangunan Pagar RSUD Pacira',
                'vendor' => 'PT. GANESA INOVASI',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [
                    [
                        'nama' => 'DWIKA PRIMA PRATAMA, S.T.',
                        'jabatan' => 'Ahli Muda Teknik Bangunan Gedung',
                        'nilai' => null,
                    ],
                    [
                        'nama' => 'IFALDI SAZARI, Ars',
                        'jabatan' => 'Tenaga Ahli Arsitek',
                        'nilai' => null,
                    ],
                    [
                        'nama' => 'Adam Rahlan Syakur, ST',
                        'jabatan' => 'Ahli Teknik Sipil – Surveyor',
                        'nilai' => null,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Review Desain DED Gedung Diskominfo',
                'vendor' => 'PT. ADHI CITRABHUMI UTAMA',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Pembangunan Kantor Kecamatan Rancaekek',
                'vendor' => 'PT. MULTI PRANATA MANDIRI NUSANTARA',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Penataan Venue Extreme',
                'vendor' => 'KONSULTAN PERORANGAN',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Rehab Gedung KNPI',
                'vendor' => 'PT. ITERGO BUANA UTAMA',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Pagar UPAKARTI',
                'vendor' => null,
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Interior Ruang Kerja BG',
                'vendor' => 'PT. PURNA WAHANA LESTARI',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'proses_desain',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan gardu pos upakarti',
                'vendor' => 'PT. GANESA PRATAMA CONSULTAN',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'proses_desain',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Masjid Rumah Dinas Bupati',
                'vendor' => 'PT. ITERGO BUANA UTAMA',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Penataan Kantor Dinas Pendidikan',
                'vendor' => null,
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanan Interior ruang rapat dan ruang tamu SETDA',
                'vendor' => null,
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'proses_desain',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Rehab Gedung Dispora',
                'vendor' => 'CV. IMAYA CONSULTING ENGINEERS',
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Rehab RSUD Tegalluar',
                'vendor' => null,
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Rehab Gedung SLRT',
                'vendor' => null,
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Interior Rumdin Wakil Bupati',
                'vendor' => null,
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'proses_desain',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'BG',
                'nama' => 'Perencanaan Saluran Drainase RSUD Arjasari',
                'vendor' => null,
                'pagu' => null,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'selesai',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'DED JALAN KABUPATEN WILAYAH CIWIDEY',
                'vendor' => 'PT. PURNA WAHANA LESTARI KONSULTAN',
                'pagu' => 99567000.0,
                'no_spk' => '602/3/SPK/PR.0029.03/DPUTR/2026',
                'tgl_spk' => '2026-02-02',
                'no_spmk' => '602/3/SPMK/PR.0029.03/DPUTR/2026',
                'tgl_mulai' => '2026-02-02',
                'tgl_akhir' => '2026-03-18',
                'hari' => 45,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Muhammad Syauqi Aminuddin',
                        'jabatan' => 'Team Leader',
                        'nilai' => 29000000,
                    ],
                    [
                        'nama' => 'Deddy Saputra, S.T',
                        'jabatan' => 'Asisten Tenaga Ahli Geodesi',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Gregorius',
                        'jabatan' => 'Asisten Tenaga Ahli Jalan',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Ipan Agus Maesa',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Yosep Jalaludin Rahmat',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Rifa Agus Septiana',
                        'jabatan' => 'Drafter',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Arif Abdul Rahman',
                        'jabatan' => 'Operator',
                        'nilai' => 3000000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'DED JALAN KABUPATEN WILAYAH SOREANG',
                'vendor' => 'PT. ADHI CITRABHUMI UTAMA',
                'pagu' => 99567000.0,
                'no_spk' => '602/1/SPK/PR.0029.01/DPUTR/2026',
                'tgl_spk' => '2026-01-19',
                'no_spmk' => '602/1/SPMK/PR.0029.01/DPUTR/2026',
                'tgl_mulai' => '2026-01-19',
                'tgl_akhir' => '2026-03-04',
                'hari' => 45,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Lili Siswanto',
                        'jabatan' => 'Team Leader',
                        'nilai' => 20000000,
                    ],
                    [
                        'nama' => 'Adam Rahlab Syakur, S.T.',
                        'jabatan' => 'Asisten Tenaga Ahli Jalan',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Faisal Jurdiansyah',
                        'jabatan' => 'Asisten Tenaga Ahli Geodesi',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Rival Ramashan',
                        'jabatan' => 'Surveyor',
                        'nilai' => 3000000,
                    ],
                    [
                        'nama' => 'Hanafi Aldiansyah',
                        'jabatan' => 'Surveyor',
                        'nilai' => 3000000,
                    ],
                    [
                        'nama' => 'Imam Saepulloh',
                        'jabatan' => 'Drafter',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Abu Rizal',
                        'jabatan' => 'Operator',
                        'nilai' => 3000000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'DED JALAN KABUPATEN WILAYAH CIPARAY',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => 99511500.0,
                'no_spk' => '602/6/SPK/PR.0029.06/DPUTR/2026',
                'tgl_spk' => '2026-02-02',
                'no_spmk' => '602/6/SPMK/PR.0029.06/DPUTR/2026',
                'tgl_mulai' => '2026-02-02',
                'tgl_akhir' => '2026-03-18',
                'hari' => 45,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Rian Hidayat, S.T.',
                        'jabatan' => 'Team Leader',
                        'nilai' => 20000000,
                    ],
                    [
                        'nama' => 'Andi Anwar, S.T',
                        'jabatan' => 'Asisten Tenaga Ahli Geodesi',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Rianto Sumalu',
                        'jabatan' => 'Asisten Tenaga Ahli Jalan',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Gelar Santika',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Irsal Anoval',
                        'jabatan' => 'Surveyor',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Arif Permana',
                        'jabatan' => 'Drafter',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Hapuidin Saputra',
                        'jabatan' => 'Operator',
                        'nilai' => 3000000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'DED JALAN KABUPATEN WILAYAH CILEUNYI',
                'vendor' => 'PT. MARTHA TRIA SELARAS',
                'pagu' => 99456000.0,
                'no_spk' => '602/8/SPK/PR.0029.08/DPUTR/2026',
                'tgl_spk' => '2026-02-02',
                'no_spmk' => '602/8/SPMK/PR.0029.08/DPUTR/2026',
                'tgl_mulai' => '2026-02-02',
                'tgl_akhir' => '2026-03-18',
                'hari' => 45,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Gan Gan Moga Syahid',
                        'jabatan' => 'Team Leader',
                        'nilai' => 20000000,
                    ],
                    [
                        'nama' => 'Isra Cardova',
                        'jabatan' => 'Asisten Tenaga Ahli Geodesi',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Andi Asmiryani Wulansari, S.T.',
                        'jabatan' => 'Asisten Tenaga Ahli Jalan',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Nurjaman',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Zia Muhammad Rustadi',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Hilaman Parid Mubaroq',
                        'jabatan' => 'Drafter',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Yusri Qorinah',
                        'jabatan' => 'Operator',
                        'nilai' => 3000000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'DED JALAN KABUPATEN WILAYAH BANJARAN',
                'vendor' => 'PT. HERANDAS ENGINEER SYSTEM',
                'pagu' => 99678000.0,
                'no_spk' => '602/11/SPK/PR.0029.11/DPUTR/2026',
                'tgl_spk' => '2026-02-02',
                'no_spmk' => '602/11/SPMK/PR.0029.11/DPUTR/2026',
                'tgl_mulai' => '2026-02-02',
                'tgl_akhir' => '2026-03-18',
                'hari' => 45,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Ahmad Sobari, ST',
                        'jabatan' => 'Team Leader',
                        'nilai' => 20000000,
                    ],
                    [
                        'nama' => 'Ahmad Jalaludin, ST',
                        'jabatan' => 'Asisten Tenaga Ahli Geodesi',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'RIDWAN SALEH, ST',
                        'jabatan' => 'Asisten Tenaga Ahli Teknik Jalan',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Anas Wahyudin',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Teddy Herdiana',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Muhammad Rizman',
                        'jabatan' => 'Drafter',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Noviani Karlina',
                        'jabatan' => 'Operator',
                        'nilai' => 3000000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'PERENCANAAN TEKNIS JALAN WILAYAH BALEENDAH',
                'vendor' => 'PT. MULTI PRANATA MANDIRI NUSANTARA',
                'pagu' => 99511500.0,
                'no_spk' => '602/15/SPK/PR.0029.15/DPUTR/2026',
                'tgl_spk' => '2026-02-02',
                'no_spmk' => '602/15/SPMK/PR.0029.15/DPUTR/2026',
                'tgl_mulai' => '2026-02-03',
                'tgl_akhir' => '2026-04-03',
                'hari' => 60,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Boby Herma Agustina, S.T.',
                        'jabatan' => 'Team Leader',
                        'nilai' => 18000000,
                    ],
                    [
                        'nama' => 'TB. Dwi Mansur Rias',
                        'jabatan' => 'Asisten Tenaga Ahli',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Ahmad Fadil Amini',
                        'jabatan' => 'Surveyor',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Andri Kusnadi',
                        'jabatan' => 'Surveyor',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Teguh Pujiono',
                        'jabatan' => 'Drafter',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Yoseph Maulana Nugraha',
                        'jabatan' => 'Operator',
                        'nilai' => 2750000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'PERENCANAAN TEKNIS JALAN WILAYAH MARGAHAYU',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => 99622500.0,
                'no_spk' => '602/22/SPK/PR.0029.22/DPUTR/2026',
                'tgl_spk' => '2026-02-02',
                'no_spmk' => '602/22/SPMK/PR.0029.22/DPUTR/2026',
                'tgl_mulai' => '2026-02-03',
                'tgl_akhir' => '2026-04-03',
                'hari' => 60,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Tedi Komara Wijaya, S.T',
                        'jabatan' => 'Team Leader',
                        'nilai' => 18000000,
                    ],
                    [
                        'nama' => 'Zulham, S.T',
                        'jabatan' => 'Asisten Tenaga Ahli',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Tomy Marcello',
                        'jabatan' => 'Surveyor',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'M. Hirzil Imani SK',
                        'jabatan' => 'Surveyor',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Teguh Pujiono',
                        'jabatan' => 'Drafter',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Ai Nugraha',
                        'jabatan' => 'Operator',
                        'nilai' => 5500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'DESAIN TROTOAR KABUPATEN BANDUNG',
                'vendor' => 'PT. BINARTHAMA KHARISMA',
                'pagu' => 99666900.0,
                'no_spk' => '602/26/SPK/PR.0029.26/DPUTR/2026',
                'tgl_spk' => '2026-02-02',
                'no_spmk' => '602/26/SPMK/PR.0029.26/DPUTR/2026',
                'tgl_mulai' => '2026-02-03',
                'tgl_akhir' => '2026-04-03',
                'hari' => 60,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Andi Fahmi Fadillah, S.T.',
                        'jabatan' => 'Team Leader',
                        'nilai' => 19270000,
                    ],
                    [
                        'nama' => 'Lilik Hadi Priyono, S.T.',
                        'jabatan' => 'Asisten Tenaga Ahli',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Ade Rana Sanjaya',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Alek Efendi',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Ari Sadewa Surya Putra',
                        'jabatan' => 'Drafter',
                        'nilai' => 5000000,
                    ],
                    [
                        'nama' => 'Sela Setiani',
                        'jabatan' => 'Operator',
                        'nilai' => 3000000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'PERENCANAAN TEKNIS JEMBATAN WILAYAH TENGAH KABUPATEN BANDUNG',
                'vendor' => 'PT. HERANDAS ENGINEER SYSTEM',
                'pagu' => 99761250.0,
                'no_spk' => '602/1/SPK/PR.0029.02/DPUTR/2026',
                'tgl_spk' => '2026-01-20',
                'no_spmk' => '602/1/SPMK/PR.0029.02/DPUTR/2026',
                'tgl_mulai' => '2026-01-21',
                'tgl_akhir' => '2026-02-09',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Roni Rachdian',
                        'jabatan' => 'Team Leader/Ahli Muda Jembatan',
                        'nilai' => 20000000,
                    ],
                    [
                        'nama' => 'Yusi Hisani, S.T.',
                        'jabatan' => 'Asisten Tenaga Ahli Struktur',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Rian Hendriawan, S.T.',
                        'jabatan' => 'Asisten Tenaga Ahli Geoteknik',
                        'nilai' => 8500000,
                    ],
                    [
                        'nama' => 'Muhammad Ma\'ruf',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Tata Tazillah Putra',
                        'jabatan' => 'Surveyor',
                        'nilai' => 6000000,
                    ],
                    [
                        'nama' => 'Muhammad Solihin',
                        'jabatan' => 'Drafter',
                        'nilai' => 3000000,
                    ],
                    [
                        'nama' => 'Evan Krisna',
                        'jabatan' => 'Operator',
                        'nilai' => 3000000,
                    ],
                    [
                        'nama' => 'Siti Masitoh',
                        'jabatan' => 'Administrasi',
                        'nilai' => null,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH SOREANG',
                'vendor' => null,
                'pagu' => 99983250.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH MARGAHAYU',
                'vendor' => null,
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH CICALENGKA',
                'vendor' => null,
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH CIPARAY',
                'vendor' => null,
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH BALEENDAH',
                'vendor' => null,
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Boby Herma Agustina',
                        'jabatan' => 'Team Leader',
                        'nilai' => null,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH BANJARAN',
                'vendor' => null,
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH PANGALENGAN',
                'vendor' => null,
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH CIWIDEY',
                'vendor' => null,
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'JL',
                'nama' => 'SURVEY KONDISI JALAN WILAYAH MAJALAYA',
                'vendor' => null,
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Penyusunan Outline pada Kawasan Genangan Wilayah Dayeuhkolot',
                'vendor' => 'PT. PURNA WAHANA LESTARI KONSULTAN',
                'pagu' => 99335000.0,
                'no_spk' => '602.1/03/SPK/JP.DR.05.01/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.03/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Agus Bramiana',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Dede Nurdin',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Arief Yudha Prayoga',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Hendi Gunawan',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Rizma Giani Sasqia',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sumarno',
                        'jabatan' => 'Surveyor 5',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Aldi Prianto',
                        'jabatan' => 'Surveyor 6',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Tubagus Ibnu Sabil',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Gea Sentanu Wanggi Segara',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Tessa Rizkya',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Mirawati',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Pembangunan Drainase Lingkungan Wilayah 1',
                'vendor' => 'PT. ADHI CITRABHUMI UTAMA',
                'pagu' => 99612500.0,
                'no_spk' => '602.1/03/SPK/JP.DPL.12.01/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.DPL.12.01/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Herdi Maulana',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Revi Iqsan Maulana',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Muhammad Ziya\'ul Haq',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dudung Abdul Karim',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Alan Zaelani',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sopian',
                        'jabatan' => 'Surveyor 5',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Bambang Supriyadi',
                        'jabatan' => 'Surveyor 6',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Yan Septian',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Lusi Astria',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Irwan Muhamad Ramdan',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sinta Nuriyah',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Pembangunan Drainase Perkotaan Wilayah 1',
                'vendor' => 'PT. JASAPLAN REKANAN UTAMA',
                'pagu' => 99501500.0,
                'no_spk' => '602.1/03/SPK/JP.DPL.12.02/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.DPL.12.02/DPUTR/TA. 2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Agus Muchyidin',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Asep Ikbal',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ivdal Ardian',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Jilan Fairuz Agni',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Riana Yusuf Nugraha',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Farizki Muhamad Romadon',
                        'jabatan' => 'Surveyor 5',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Satrya Eka Purnama Rismawan',
                        'jabatan' => 'Surveyor 6',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Siti Zahra Fauziah',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Uat Supriatna',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Eep Saepul',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Arungga Iqbalysyah',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Pembangunan Drainase Perkotaan Wilayah 2',
                'vendor' => 'PT. PURNA WAHANA LESTARI',
                'pagu' => 74526500.0,
                'no_spk' => '602.1/03/SPK/JP.DPL.12.03/DPUTR/2026 ',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.DPL.12.03/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Winda Diana Sri',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Deden Supriyadi',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Eko Ari Sandi',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Jiva Hidayat',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Asep Andana',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ridwan Jujun Saparudin',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Agus',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Rudi Zazri',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Naila Khansan Putri Ramdani',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Pembangunan Drainase Perkotaan Wilayah 3',
                'vendor' => 'PT. HERANDAS ENGINEER SYSTEM',
                'pagu' => 74737400.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.03/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SMPK/JP.SPALD.05.03/DPUTR/2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Pujo Basuki',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Encep Sudrajat',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ismi Vancana',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Roni Permana',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dikdik Hardikman',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ervan Fahrijal',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Muhammad Adhianto',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ari Maulana Sidik',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Danny Gaida Tera Elgar',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Pembangunan Drainase Perkotaan Wilayah 4',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => 74587500.0,
                'no_spk' => '602.1/03/SPK/JP.DPL.12.03/DPUTR/2026 ',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.DPL.12.03/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Surya Mahendra, ST',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Andry Sutriadi',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dicky Karyadisastra',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sardi',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Yudiana Mucharam',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Toni Andriawan',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Irfan Maulana Efendi',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Aria Nugraha',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Reni Mulyani',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Pembangunan Drainase Perkotaan Wilayah 6',
                'vendor' => 'PT. MARTHA TRIA SELARAS',
                'pagu' => 74593100.0,
                'no_spk' => '602.1/03/SPK/JP.DPL.12.06/DPUTR/TA.2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.DPL.12.06/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Frezha Nur Septian',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Darul Junansah Pujasmara',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Asril',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Eko Bambang Yunianto',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Herdian',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Riki Riyanto',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Kadiyo',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Syamsul Rais',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dindin Hasanudin',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Pembangunan Drainase Perkotaan Wilayah 7',
                'vendor' => 'PT. BINARTHAMA KHARISMA',
                'pagu' => 74681900.0,
                'no_spk' => '602.1/03/SPK/JP.DPL.12.07.DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.DPL.12.07.DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-27',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Agus Budhy Prasetyo',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Rudi Maulana',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Muhammad Restu Aufa Cahyadin',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Haifa Ruwaidah',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Deni Yogaswara',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sutiono',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Waras Warsono',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Jamaludin',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Diman Cahaya Gumilar',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 1',
                'vendor' => 'PT. ITERGO BUANA UTAMA',
                'pagu' => 74759600.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.01/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.01/DPUTR/2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Tantan Rustandi',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Faschal Fahreza',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dean Bayu Pradana',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Mutiara Rahmawati',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Arif Taufik Hidayat',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Muhammad Zaidan Hasbiallah',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ade Sony',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Fajar Ichwana',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Endang Fitriya',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 2',
                'vendor' => 'PT. ADHI CITRABHUMI UTAMA',
                'pagu' => 74748500.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.02/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.02/DPUTR/2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Risda Insan Budiman',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Iman Warisman',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Salman Abdussalam',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Suryana',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Yudi Zatnika',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Restu Gumelar',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Novi Noviyanti',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Widi Nur Sabana',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Silvi Herdiana Oktaviani',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 3',
                'vendor' => 'PT. JASAPLAN REKANAN UTAMA',
                'pagu' => 74737400.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.03/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/03/SPMK/JP.SPALD.05.03/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'A.Viranthy Dian Pertiwi',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Sofiandhy Hutauruk',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Risti Al-Zahra',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Pandega Kukuh Prayoga',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ridwan Arif',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Nabila Saharani',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dani Ramdani',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Muhamad Fadil',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dara Anggraeni',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 4',
                'vendor' => 'PT. PURNA WAHANA LESTARI',
                'pagu' => 74693000.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.04/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.04/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Lirawati',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Dadang',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Adam Mochamad Suhendar',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Iwan Setiawan',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Rahmat Saidi',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Rudi Jaelani',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Laela Fitriani',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Gatot Sugiyarto',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Mega Meliana Junjunan',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 5',
                'vendor' => 'PT. HERANDAS ENGINEER SYSTEM',
                'pagu' => 74637500.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.05/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.05/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Nurul Nindita Hapsari',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Hendi Pirmansyah',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Agus Supriatna',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Akbar',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Refi Hambali',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Azmil Firdaus',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Marcos Ey Dely, ST',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Nani Suryani',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Rina Apriani',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 6',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => 74626400.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.06/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.06/DPUTR/2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Agung Prayoga',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Yudi Suparman',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ahmad Nurkholis Majid',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Engkus Kusnandar',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Nandi Faharul Reza',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ridho Yanuar Hidayat',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dede Siti Rahmawati',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Rama Krisna Maulana',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Tania Ayunda',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 7',
                'vendor' => 'PT. MARTHA TRIA SELARAS',
                'pagu' => 74615300.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.07/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.07/DPUTR/2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Nurullah Al Faarisi',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Rafiz Iskandar',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Arief Budiman',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Cik Indi Tensik',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sahrul Maulana Yusuf',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Agung Ilyas Pratama',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Yana Gustiana',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Kaisya Rizki Nafisah',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Yuyu Wahyudin',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 8',
                'vendor' => 'PT. BINARTHAMA KHARISMA',
                'pagu' => 74661900.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.08/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.08/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Angga Kurnia Riyadi',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Aditiya Permana',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ade Hermawan',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Freddy',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Muhamad Susman Alamsyah',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Ahmad Harris Wirahadisuria',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Jazkia Ahmad Ad Dairaby',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Rano Hermawan',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sri Mutia Suciati',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 9',
                'vendor' => 'PT. ITERGO BUANA UTAMA',
                'pagu' => 74693000.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.09/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.09/DPUTR/TA.2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Andriansyah, ST',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Zidan Abdul Mutaqin',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Wawan Setiawan',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sandi Gunawan',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Reza Agustian',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Agus Hermawan',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Dani',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Rini Setianingsih',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sri Mukti Rahayu',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'DR',
                'nama' => 'Perencanaan Teknik Rencana, Kebijakan, Strategi dan Teknis Sistem Pengelolaan Air Limbah Domestik (SPALD) Wilayah 10',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => 746375900.0,
                'no_spk' => '602.1/03/SPK/JP.SPALD.05.10/DPUTR/2026',
                'tgl_spk' => '2026-01-26',
                'no_spmk' => '602.1/04/SPMK/JP.SPALD.05.10/DPUTR/2026',
                'tgl_mulai' => '2026-01-26',
                'tgl_akhir' => '2026-02-24',
                'hari' => 30,
                'status_kode' => 'review_internal',
                'personil' => [
                    [
                        'nama' => 'Sarip Hidayatulloh',
                        'jabatan' => 'Team Leader',
                        'nilai' => 22000000,
                    ],
                    [
                        'nama' => 'Andriyan',
                        'jabatan' => 'Surveyor 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Sani Ramdani',
                        'jabatan' => 'Surveyor 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Anjas Tri Haryanto',
                        'jabatan' => 'Surveyor 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Gelar Gumilar',
                        'jabatan' => 'Surveyor 4',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Arga Sukmadi',
                        'jabatan' => 'Drafter 1',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Arief Chaniago',
                        'jabatan' => 'Drafter 2',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Farid Hidayat',
                        'jabatan' => 'Drafter 3',
                        'nilai' => 4500000,
                    ],
                    [
                        'nama' => 'Vicky Aulia Gunawan',
                        'jabatan' => 'Adm',
                        'nilai' => 4500000,
                    ],
                ],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan 1 Normalisasi/restorasi saluran',
                'vendor' => 'PT. GANESA PRATAMA CONSULTAN',
                'pagu' => 49689150.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Pembangunan Embung dan Penampung Air',
                'vendor' => 'PT. DWINA KARYA UTAMA',
                'pagu' => 50000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Tanggul Sungai',
                'vendor' => 'PT. ITERGO BUANA UTAMA',
                'pagu' => 49689150.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'DED Kolam Retensi CPI',
                'vendor' => 'PT. PRIMAREKA CIPTA MANDIRI',
                'pagu' => 50000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Review Design Kolam Retensi Cikasungka',
                'vendor' => 'PT. GANESA INOVASI',
                'pagu' => 50000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Jaringan Irigasi Wilayah Sub DAS Cisangkuy',
                'vendor' => 'PT. ADHI CITRABHUMI UTAMA',
                'pagu' => 99211800.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Jaringan Irigasi Wilayah Sub DAS Ciwidey',
                'vendor' => 'PT. ADHI CITRABHUMI UTAMA',
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Jaringan Irigasi Wilayah Sub DAS Cirasea',
                'vendor' => 'PT. JASAPLAN REKANAN UTAMA',
                'pagu' => 74525400.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Jaringan Irigasi Wilayah Sub DAS Citarik',
                'vendor' => 'PT. JASAPLAN REKANAN UTAMA',
                'pagu' => 75000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Bendung Wilayah Sub DAS Cisangkuy',
                'vendor' => 'PT. PURNA WAHANA LESTARI',
                'pagu' => 75000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Bendung Wilayah Sub DAS Ciwidey',
                'vendor' => 'PT. PURNA WAHANA LESTARI',
                'pagu' => 75000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Bendung Wilayah Sub DAS Cirasea',
                'vendor' => 'PT. BINARTHAMA KHARISMA',
                'pagu' => 75000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Rehabilitasi Bendung Wilayah Sub DAS Citarik',
                'vendor' => 'PT. BINARTHAMA KHARISMA',
                'pagu' => 75000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Air Bersih Perdesaan Paket 7',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => 99611400.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
            [
                'bidang_kode' => 'IR',
                'nama' => 'Perencanaan Air Bersih Perdesaan Paket 8',
                'vendor' => 'CV. TACIBA SHIGOTO NUSANTARA',
                'pagu' => 100000000.0,
                'no_spk' => null,
                'tgl_spk' => null,
                'no_spmk' => null,
                'tgl_mulai' => null,
                'tgl_akhir' => null,
                'hari' => null,
                'status_kode' => 'review_internal',
                'personil' => [],
            ],
        ];

        foreach ($rows as $row) {
            $bidangId = $bidangIds[$row['bidang_kode']] ?? null;
            if (!$bidangId) {
                $this->command->warn("Bidang {$row['bidang_kode']} tidak ditemukan, skip.");
                continue;
            }
            $perusahaanId = $row['vendor'] ? ($vendorMap[$row['vendor']] ?? null) : null;

            // Some proyek dari Excel tidak punya no_spk → skip kalau benar null,
            // tapi tetap simpan dengan unique placeholder agar lolos unique constraint
            $noSpk = $row['no_spk'] ?: ('PLACEHOLDER-' . md5($row['nama']));

            $pekerjaan = Pekerjaan::updateOrCreate(
                [
                    'no_spk' => $noSpk,
                    'bidang_id' => $bidangId,
                    'tahun_anggaran' => 2026,
                ],
                [
                    'nama_pekerjaan' => $row['nama'],
                    'perusahaan_id' => $perusahaanId,
                    'nilai_pagu' => $row['pagu'],
                    'nilai_kontrak' => $row['pagu'],
                    'no_spmk' => $row['no_spmk'],
                    'tanggal_spk' => $row['tgl_spk'],
                    'tanggal_spmk' => $row['tgl_mulai'],
                    'tanggal_mulai' => $row['tgl_mulai'],
                    'tanggal_akhir' => $row['tgl_akhir'],
                    'hari_kerja' => $row['hari'],
                    'status_pekerjaan_id' => $statusIds[$row['status_kode']] ?? null,
                    'progres_persen' => $row['status_kode'] === 'selesai' ? 100 : 50,
                ],
            );

            // Personil
            foreach ($row['personil'] as $ps) {
                $ta = TenagaAhli::firstOrCreate(
                    ['nama' => $ps['nama']],
                    ['perusahaan_id' => $perusahaanId, 'is_active' => true],
                );
                PekerjaanPersonil::firstOrCreate(
                    ['pekerjaan_id' => $pekerjaan->id, 'tenaga_ahli_id' => $ta->id],
                    [
                        'jabatan_kontrak' => $ps['jabatan'] ?: 'Tim',
                        'nilai_honor_kontrak' => $ps['nilai'],
                        'is_active' => true,
                    ],
                );
            }
        }

        $this->command->info('RealPekerjaan2026Seeder: imported ' . count($rows) . ' proyek.');
    }
}